trigger:
  branches:
    include:
      - main  

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'

- script: |
    javac Hello.java
    java Hello
  displayName: 'Build and Run Hello.java'
